# Generated by Django 5.0.2 on 2024-02-20 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'clients_info',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Endpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint_name', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'endpoints',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=256, null=True)),
                ('client_info_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dj_fp.clientinfo')),
            ],
            options={
                'db_table': 'clients',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EndpointStates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=256)),
                ('state_reason', models.CharField(max_length=256)),
                ('state_start', models.CharField(max_length=256)),
                ('state_end', models.CharField(max_length=256)),
                ('state_id', models.CharField(max_length=256)),
                ('group_id', models.CharField(max_length=256)),
                ('reason_group', models.CharField(max_length=256)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dj_fp.client')),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dj_fp.endpoint')),
            ],
            options={
                'db_table': 'endpoint_states',
                'managed': True,
            },
        ),
    ]
